"""Add user_email to EmailAutomationRequest and other models

Revision ID: 3b0d02d565bd
Revises: 
Create Date: 2026-07-25 01:18:07.780518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b0d02d565bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_automation_requests', sa.Column('user_email', sa.String(), nullable=False))
    op.drop_index(op.f('ix_email_automation_requests_user_id'), table_name='email_automation_requests')
    op.create_index(op.f('ix_email_automation_requests_user_email'), 'email_automation_requests', ['user_email'], unique=False)
    op.drop_constraint(op.f('email_automation_requests_user_id_fkey'), 'email_automation_requests', type_='foreignkey')
    op.create_foreign_key(None, 'email_automation_requests', 'users', ['user_email'], ['email'])
    op.drop_column('email_automation_requests', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_automation_requests', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'email_automation_requests', type_='foreignkey')
    op.create_foreign_key(op.f('email_automation_requests_user_id_fkey'), 'email_automation_requests', 'users', ['user_id'], ['user_id'])
    op.drop_index(op.f('ix_email_automation_requests_user_email'), table_name='email_automation_requests')
    op.create_index(op.f('ix_email_automation_requests_user_id'), 'email_automation_requests', ['user_id'], unique=False)
    op.drop_column('email_automation_requests', 'user_email')
    # ### end Alembic commands ###
