"""Add user_email to EmailAutomationRequest and other models

Revision ID: 9ff9d4087f54
Revises: 3b0d02d565bd
Create Date: 2026-07-25 01:27:27.706694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff9d4087f54'
down_revision: Union[str, Sequence[str], None] = '3b0d02d565bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_templates', sa.Column('user_email', sa.String(), nullable=True))
    op.drop_index(op.f('ix_user_templates_owner_user_id'), table_name='user_templates')
    op.drop_index(op.f('idx_user_template_role_unique'), table_name='user_templates')
    op.create_index('idx_user_template_role_unique', 'user_templates', ['template_role', 'user_email'], unique=True)
    op.create_index(op.f('ix_user_templates_user_email'), 'user_templates', ['user_email'], unique=False)
    op.drop_constraint(op.f('user_templates_owner_user_id_fkey'), 'user_templates', type_='foreignkey')
    op.create_foreign_key(None, 'user_templates', 'users', ['user_email'], ['email'])
    op.drop_column('user_templates', 'owner_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_templates', sa.Column('owner_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_templates', type_='foreignkey')
    op.create_foreign_key(op.f('user_templates_owner_user_id_fkey'), 'user_templates', 'users', ['owner_user_id'], ['user_id'])
    op.drop_index(op.f('ix_user_templates_user_email'), table_name='user_templates')
    op.drop_index('idx_user_template_role_unique', table_name='user_templates')
    op.create_index(op.f('idx_user_template_role_unique'), 'user_templates', ['template_role', 'owner_user_id'], unique=True)
    op.create_index(op.f('ix_user_templates_owner_user_id'), 'user_templates', ['owner_user_id'], unique=False)
    op.drop_column('user_templates', 'user_email')
    # ### end Alembic commands ###
