"""Rename api_key to app_password in user_email_info

Revision ID: aa47061e5f9a
Revises: cf646e9b6938
Create Date: 2026-07-25 03:48:11.483335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa47061e5f9a'
down_revision: Union[str, Sequence[str], None] = 'cf646e9b6938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_email_info', sa.Column('encrypted_app_password', sa.String(), nullable=False))
    op.drop_column('user_email_info', 'encrypted_api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_email_info', sa.Column('encrypted_api_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user_email_info', 'encrypted_app_password')
    # ### end Alembic commands ###
