"""Add user_email to EmailAutomationRequest and other models

Revision ID: bf2c6b31f695
Revises: 9ff9d4087f54
Create Date: 2026-07-25 01:46:54.063476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf2c6b31f695'
down_revision: Union[str, Sequence[str], None] = '9ff9d4087f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_tokens', sa.Column('email', sa.String(), nullable=False))
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_email'), 'password_reset_tokens', ['email'], unique=False)
    op.drop_constraint(op.f('password_reset_tokens_user_id_fkey'), 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'password_reset_tokens', 'users', ['email'], ['email'])
    op.drop_column('password_reset_tokens', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_tokens', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('password_reset_tokens_user_id_fkey'), 'password_reset_tokens', 'users', ['user_id'], ['user_id'])
    op.drop_index(op.f('ix_password_reset_tokens_email'), table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.drop_column('password_reset_tokens', 'email')
    # ### end Alembic commands ###
