"""Standardize on user_email for all foreign keys

Revision ID: cf646e9b6938
Revises: bf2c6b31f695
Create Date: 2026-07-25 01:56:31.501541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf646e9b6938'
down_revision: Union[str, Sequence[str], None] = 'bf2c6b31f695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_automation_requests', sa.Column('reviewed_by_admin_email', sa.String(), nullable=True))
    op.drop_constraint(op.f('email_automation_requests_reviewed_by_admin_id_fkey'), 'email_automation_requests', type_='foreignkey')
    op.create_foreign_key(None, 'email_automation_requests', 'users', ['reviewed_by_admin_email'], ['email'])
    op.drop_column('email_automation_requests', 'reviewed_by_admin_id')
    op.add_column('job_templates', sa.Column('user_email', sa.String(), nullable=True))
    op.drop_constraint(op.f('uq_template_role_per_user'), 'job_templates', type_='unique')
    op.create_unique_constraint('uq_template_role_per_user', 'job_templates', ['template_role', 'user_email'])
    op.drop_constraint(op.f('job_templates_owner_user_id_fkey'), 'job_templates', type_='foreignkey')
    op.create_foreign_key(None, 'job_templates', 'users', ['user_email'], ['email'])
    op.drop_column('job_templates', 'owner_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_templates', sa.Column('owner_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'job_templates', type_='foreignkey')
    op.create_foreign_key(op.f('job_templates_owner_user_id_fkey'), 'job_templates', 'users', ['owner_user_id'], ['user_id'])
    op.drop_constraint('uq_template_role_per_user', 'job_templates', type_='unique')
    op.create_unique_constraint(op.f('uq_template_role_per_user'), 'job_templates', ['template_role', 'owner_user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('job_templates', 'user_email')
    op.add_column('email_automation_requests', sa.Column('reviewed_by_admin_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'email_automation_requests', type_='foreignkey')
    op.create_foreign_key(op.f('email_automation_requests_reviewed_by_admin_id_fkey'), 'email_automation_requests', 'users', ['reviewed_by_admin_id'], ['user_id'])
    op.drop_column('email_automation_requests', 'reviewed_by_admin_email')
    # ### end Alembic commands ###
