"""Multi-tenant workflow with approval-based access

Revision ID: multi_tenant_001
Revises: 082b8b0cc11b
Create Date: 2026-07-21 00:00:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'multi_tenant_001'
down_revision: Union[str, Sequence[str], None] = '082b8b0cc11b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create enum types
    user_role_enum = postgresql.ENUM('admin', 'visitor', 'customer', name='userrole')
    user_role_enum.create(op.get_bind())
    
    template_scope_enum = postgresql.ENUM('default', 'customer', name='templatescope')
    template_scope_enum.create(op.get_bind())
    
    request_status_enum = postgresql.ENUM('pending', 'approved', 'rejected', name='requeststatus')
    request_status_enum.create(op.get_bind())
    
    # Step 1: Add new columns to users table
    op.add_column('users', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('linkedin_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('linkedin_url_normalized', sa.String(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    
    # Step 2: Populate user_id with sequence values
    op.execute("""
        UPDATE users 
        SET user_id = sub.row_num
        FROM (
            SELECT email, ROW_NUMBER() OVER (ORDER BY email) as row_num
            FROM users
        ) sub
        WHERE users.email = sub.email
    """)
    
    # Step 3: Make user_id not null and set as primary key
    op.alter_column('users', 'user_id', nullable=False)
    op.execute("ALTER TABLE users DROP CONSTRAINT users_pkey")
    op.execute("ALTER TABLE users ADD CONSTRAINT users_pkey PRIMARY KEY (user_id)")
    
    # Step 4: Update role column to use new enum
    op.alter_column('users', 'role', type_=user_role_enum, nullable=False, server_default='visitor')
    
    # Step 5: Add indexes and constraints
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_linkedin_url_normalized'), 'users', ['linkedin_url_normalized'], unique=True)
    op.create_unique_constraint('uq_user_email_linkedin', 'users', ['email', 'linkedin_url_normalized'])
    
    # Step 6: Set default values for timestamps
    op.execute("""
        UPDATE users 
        SET created_at = NOW(), updated_at = NOW()
        WHERE created_at IS NULL
    """)
    op.alter_column('users', 'created_at', nullable=False)
    op.alter_column('users', 'updated_at', nullable=False)
    
    # Step 7: Update password_reset_tokens to use user_id instead of email
    op.add_column('password_reset_tokens', sa.Column('user_id', sa.Integer(), nullable=True))
    
    # Map email to user_id
    op.execute("""
        UPDATE password_reset_tokens prt
        SET user_id = u.user_id
        FROM users u
        WHERE prt.email = u.email
    """)
    
    op.alter_column('password_reset_tokens', 'user_id', nullable=False)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.drop_column('password_reset_tokens', 'email')
    
    # Step 8: Create new tables
    # Template role types
    op.create_table(
        'template_role_types',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('code', sa.String(), nullable=False),
        sa.Column('display_name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id', name='template_role_types_pkey'),
        sa.UniqueConstraint('code', name='uq_template_role_types_code')
    )
    op.create_index(op.f('ix_template_role_types_id'), 'template_role_types', ['id'], unique=False)
    op.create_index(op.f('ix_template_role_types_code'), 'template_role_types', ['code'], unique=True)
    
    # User templates
    op.create_table(
        'user_templates',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('owner_user_id', sa.Integer(), nullable=True),
        sa.Column('template_role_type_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('context', sa.String(), nullable=False),
        sa.Column('filename', sa.String(), nullable=False),
        sa.Column('cv_bytes', sa.LargeBinary(), nullable=False),
        sa.Column('template_scope', template_scope_enum, nullable=False, server_default='customer'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], name='fk_user_templates_owner_user_id'),
        sa.ForeignKeyConstraint(['template_role_type_id'], ['template_role_types.id'], name='fk_user_templates_template_role_type_id'),
        sa.PrimaryKeyConstraint('id', name='user_templates_pkey')
    )
    op.create_index(op.f('ix_user_templates_id'), 'user_templates', ['id'], unique=False)
    op.create_index(op.f('ix_user_templates_owner_user_id'), 'user_templates', ['owner_user_id'], unique=False)
    
    # User email info
    op.create_table(
        'user_email_info',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('sender_email', sa.String(), nullable=False),
        sa.Column('sender_name', sa.String(), nullable=False),
        sa.Column('encrypted_app_password', sa.String(), nullable=False),
        sa.Column('email_provider', sa.String(), nullable=False, server_default='gmail'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='fk_user_email_info_user_id'),
        sa.PrimaryKeyConstraint('id', name='user_email_info_pkey'),
        sa.UniqueConstraint('user_id', name='uq_user_email_info_user_id')
    )
    op.create_index(op.f('ix_user_email_info_id'), 'user_email_info', ['id'], unique=False)
    op.create_index(op.f('ix_user_email_info_user_id'), 'user_email_info', ['user_id'], unique=True)
    
    # Email automation requests
    op.create_table(
        'email_automation_requests',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('user_email_info_id', sa.Integer(), nullable=False),
        sa.Column('status', request_status_enum, nullable=False, server_default='pending'),
        sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('reviewed_by_admin_id', sa.Integer(), nullable=True),
        sa.Column('admin_notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='fk_email_automation_requests_user_id'),
        sa.ForeignKeyConstraint(['user_email_info_id'], ['user_email_info.id'], name='fk_email_automation_requests_user_email_info_id'),
        sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['users.user_id'], name='fk_email_automation_requests_reviewed_by_admin_id'),
        sa.PrimaryKeyConstraint('id', name='email_automation_requests_pkey')
    )
    op.create_index(op.f('ix_email_automation_requests_id'), 'email_automation_requests', ['id'], unique=False)
    op.create_index(op.f('ix_email_automation_requests_user_id'), 'email_automation_requests', ['user_id'], unique=False)
    
    # Step 9: Insert default template role types
    op.execute("""
        INSERT INTO template_role_types (code, display_name, description, is_active, sort_order, created_at, updated_at)
        VALUES 
        ('software_engineer', 'Software Engineer', 'Templates for software engineering positions', true, 1, NOW(), NOW()),
        ('data_scientist', 'Data Scientist', 'Templates for data science positions', true, 2, NOW(), NOW()),
        ('product_manager', 'Product Manager', 'Templates for product management positions', true, 3, NOW(), NOW()),
        ('designer', 'Designer', 'Templates for design positions', true, 4, NOW(), NOW())
    """)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop new tables
    op.drop_table('email_automation_requests')
    op.drop_table('user_email_info')
    op.drop_table('user_templates')
    op.drop_table('template_role_types')
    
    # Restore password_reset_tokens
    op.add_column('password_reset_tokens', sa.Column('email', sa.String(), nullable=False))
    op.execute("""
        UPDATE password_reset_tokens prt
        SET email = u.email
        FROM users u
        WHERE prt.user_id = u.user_id
    """)
    op.alter_column('password_reset_tokens', 'email', nullable=False)
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_column('password_reset_tokens', 'user_id')
    
    # Remove constraints and indexes from users
    op.drop_constraint('uq_user_email_linkedin', 'users', type_='unique')
    op.drop_index(op.f('ix_users_linkedin_url_normalized'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    
    # Remove new columns from users
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'linkedin_url_normalized')
    op.drop_column('users', 'linkedin_url')
    op.drop_column('users', 'user_id')
    
    # Restore email as primary key
    op.execute("ALTER TABLE users DROP CONSTRAINT users_pkey")
    op.execute("ALTER TABLE users ADD CONSTRAINT users_pkey PRIMARY KEY (email)")
    
    # Drop enum types
    request_status_enum = postgresql.ENUM('pending', 'approved', 'rejected', name='requeststatus')
    request_status_enum.drop(op.get_bind())
    
    template_scope_enum = postgresql.ENUM('default', 'customer', name='templatescope')
    template_scope_enum.drop(op.get_bind())
    
    user_role_enum = postgresql.ENUM('admin', 'visitor', 'customer', name='userrole')
    user_role_enum.drop(op.get_bind())
    
    # ### end Alembic commands ###
